### ISSUE TITLE
TXA Landscape addon throws errors in bForartists 3.0

### ISSUE THREAD

**Issue by trilobite53** [nerk987/txa_ant#11] opened 2021-12-08 17:20 UTC
First, this is a remarkable addon. Thank you so much for making it available to the Blender community.
Your addon works flawlessly in Blender 3.0. But this report is about errors and dysfunction in bforartists 3.0.
I have already reported the problem on the bforartists forum. They recommended I post here.

Thanks.

I am going to present a series of screenshots that should illustrate the problem
![txa_landscape_1](https://user-images.githubusercontent.com/95769108/145252573-288cd2e3-26eb-431b-9852-0b7a78b5da96.jpg)
The TXA Landscape panel displays normally(above).

![txa_landscape_2](https://user-images.githubusercontent.com/95769108/145252855-d6f36ebe-67a2-470f-9c2d-1a3e5fb179b4.jpg)
After hitting the “Landscape” button, a terrain mesh is added and throws the displayed error (above).

![txa_landscape_3](https://user-images.githubusercontent.com/95769108/145252997-ab861681-3f53-45a9-9e18-422bff8119d4.jpg)
After selecting one of the available “Preferred Material” presets (in this case, Alpine) this error is displayed (above).
![txa_landscape_4](https://user-images.githubusercontent.com/95769108/145253127-5cbd61c0-2d15-4679-9927-67eb57fa6211.jpg)
Rendering produces the result displayed above.

Here are my specs…
==========================================
= Blender 3.1.0 Alpha System Information =
==========================================
Blender:
==========================================
version: 3.1.0 Alpha, branch: Unknown, commit date: Unknown Unknown, hash: Unknown, type: Unknown
build date: Unknown, Unknown
platform: ‘Windows-10-10.0.22000-SP0’
binary path: ‘C:\\Program Files\\Bforartists 3\\3.0.0\\bforartists.exe’
build cflags: Unknown
build cxxflags: Unknown
build linkflags: Unknown
build system: Unknown

Python:
==========================================
version: 3.9.7 (default, Oct 11 2021, 19:31:28) [MSC v.1916 64 bit (AMD64)]
Python (External Binary):
==========================================
binary path: ‘C:\\Program Files\\Bforartists 3\\3.0.0\\3.1\\python\\bin\\python.EXE’
version: Python 3.9.7

GPU:
==========================================
renderer:             ‘NVIDIA GeForce RTX 2060/PCIe/SSE2’
vendor:                ‘NVIDIA Corporation’
version: ‘4.5.0 NVIDIA 496.76’

System
==========================================
Processor    AMD Ryzen 7 3700X 8-Core Processor                3.59 GHz
Installed RAM    32.0 GB
Windows 11 Pro  64-bit operating system, x64-based processor

**Comment by ReinerBforartists** [comment] 2021-12-08 17:51
Thanks for reporting the problem here trilobite53. We have meanwhile found the cause. It was indeed a problem at our end. We had renamed the "Subsurface Radius" prop in the principled shader to "Subsurface Radius (R,G,B)" to make its purpose a bit more clear. And broke the API by that. 

Sorry for the trouble. As told, the problem was at our end. And is now fixed.

**Closed as completed** 2024-03-22 11:38 UTC
